<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <style>
  
	 .clearfix:after {
		content: ".";
		display: block;
		clear: both;
		visibility: hidden;
		line-height: 0;
		height: 0;
	}
	 
	.clearfix {
		display: inline-block;
	}
	 
	html[xmlns] .clearfix {
		display: block;
	}
	 
	* html .clearfix {
		height: 1%;
	}
  
	*{margin:0; padding:0; border:0; list-style-type:none}
	#all{ width:900px; margin:0 auto; background:red}
	#principal{background:orange}
	#menu{float:left; width:200px; background:green}
	#conteudo{float:left; width:700px; background:silver}
  </style>
</head>
<body>

	<div id="all">
		<div id="topo">
			Topo
		</div>
		<div id="principal" class="clearfix">
			<div id="menu">
				Menu
			</div>
			<div id="conteudo">

<?php echo $this->layout()->content ?>

			</div>
		</div>
	</div>

</body>
</html>
