<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">
        
          
          <!--/stories-->
		  <div class="row">    
            <br>
            <div class="col-md-10 col-sm-9">
              <h3></h3>
              <br><br>
            </div>
          </div>
          <hr>
          <!--/stories-->   
          
        </div>
      </div>
                                                                                       
	                                                
                                                      
   	</div><!--/col-12-->
  </div>
</div>
